# Helipad data
data = {
    "-1": {
        "name": "St. Marys Health Care Systems Heliport",
        "location": "1230 BAXTER ST.ATHENS, GA 30606-3791",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Mary.png",
        "latitude": "33.9484611",
        "longitude": "-83.4070611",
    },
    "0": {
        "name": "St. Marys Health Care Systems Heliport",
        "location": "1230 BAXTER ST.ATHENS, GA 30606-3791",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Mary.png",
        "latitude": "33.9484611",
        "longitude": "-83.4070611",
    },
    "2": {
        "name": "Ruffwood Heliport",
        "id": "73GA",
        "location": "1425 North Harris Ridge, Atlanta, GA 30327",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Ruffwood.png",
        "latitude": "33.8825000",
        "longitude": "-84.4358333",
    },
    "3": {
        #Landing for all scenarios except 4 Medevac II
        "name": "Emory University Hospital Heliport",
        "id": "7GA8",
        "location": "1364 CLIFTON ROAD NE, ATLANTA, GA 30322",
        "hasHospital": True,
        "nearest": False,
        "nominal": True,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        # "latitude": "33.7919194", original
        # "longitude": "-84.3225861", original
        "latitude": "33.795954485398155", #offset for visibility to Chappell Park baseball fields
        "longitude": "-84.32677430346087", #offset to chappel Park baseball fields
    },
    # "4": {
    #     "name": "Emory University Hospital Midtown Heliport",
    #     "id": "GA64",
    #     "location": "550 PEACHTREE ST. N.E.,ATLANTA, GA 30308",
    #     "hasHospital": True,
    #     "nearest": False,
    #     "nominal": False,
    #     "nominal_departure": False,
    #     "image1": "../static/HAIInterface/img/Mary1.png",
    #     "image2": "../static/HAIInterface/img/Emory.png",
    #     "latitude": "33.7686667",
    #     "longitude": "-84.3868750",
    # }, 
    "5": {
         # Nearest for high workload scenario (AI suggestion)
        "name": "Hilton Garden Inn Downtown Heliport",
        "id": "7GA6",
        "location": "300 MARIETTA ST. NW, STE 304, ATLANTA, GA 30313",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7619444",
        "longitude": "-84.3955556",
    },
    "6": {
        "name": "Childrens Health Care Atlanta at Scottish Rite Heliport",
        "id": "GA11",
        "location": "1001 JOHNSON FERRY RD NE, ATLANTA, GA 30342",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.9072222",
        "longitude": "-84.3541667",
    },
    "7": {
        "name": "Children's Healthcare of Atlanta-Egleston Heliport",
        "id": "60GA",
        "location": "1405 CLIFTON RD,ATLANTA, GA 30322",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7940833",
        "longitude": "-84.3192833",
    },
    "8": {
        "name": "Bridge Building Heliport",
        "id": "GA66",
        "location": "11968 PEACHTREE RD,ATLANTA, GA 30309",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.8096694",
        "longitude": "-84.3951500",
    },
    "9": {
        "name": "WGCL-TV Heliport",
        "id": "31GA",
        "location": "425 14TH STREET NW ATLANTA, GA 30318",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7873528",
        "longitude": "-84.4010528",
    },
    "10": {
        "name": "Interstate North Heliport",
        "id": "GA54",
        "location": "300 INTERSTATE N, SUITE 285 ATLANTA, GA 30339",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.9008667",
        "longitude": "-84.4683361",

    },
    #  "11": {
    #     "name": "Southside Medical",
    #     "id": "GA85",
    #     "location": "1 MARTIN LUTHER KING DRIVE ATLANTA, GA 30334",
    #     "hasHospital": True,
    #     "nearest": False,
    #     "nominal": False,
    #     "nominal_departure": False,
    #     "image1": "../static/HAIInterface/img/Mary1.png",
    #     "image2": "../static/HAIInterface/img/Emory.png",
    #     "latitude": "33.7474278",
    #     "longitude": "-84.3882583",
    # }, 
    "11": {
        "name": "Rabbit Hole Heliport",
        "id": "52GA",
        "location": "2100 SUGAR CREEK TRAIL BUCKHEAD, GA 30625",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.5380556",
        "longitude": "-84.4744444",
    },
    "12": {
        "name": "St Joseph's Hospital Heliport",
        "id": "GA52",
        "location": "11705 Mercy Blvd. Savannah, GA 31419",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.9083639",
        "longitude": "-84.3510194",
    },
    "14": {
        "name": "WSB-TV Heliport",
        "id": "7GA1",
        "location": "1601 W Peachtree St N.e. Atlanta, GA 30309",
        "hasHospital": False,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7992717",
        "longitude": "-84.3855556",
    },
    "15": {
        
        "name": "Northside Hospital Heliport",
        "id": "GA55",
        "location": "1000 JOHNSON FERRY RD NE ATLANTA, GA 30342",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.9098500",
        "longitude": "-84.3557639",
    },
    "16": {
        "name": "Piedmont Atlanta Hospital Heliport",
        "id": "2GA6",
        "location": "1968 PEACHTREE LANE ATLANTA, GA 30309",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.8080000",
        "longitude": "-84.3941389",
    },
    "17": {
        "name": "Legacy Medical Center Heliport",
        "id": "9GE8",
        "location": "501 FAIRBURN RD SW ATLANTA, GA 30331",
        "hasHospital": True,
        "nearest": False,
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7409056",
        "longitude": "-84.5125472",
    },
    "18": {
        "name": "The Barclay Condos Heliport",
        "id": "2GE9",
        "location": "3530 PIEDMONT ROAD PH1 ATLANTA, GA 30305",
        "hasHospital": False,
        "nearest": False,  
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.8490944",  
        "longitude": "-84.3796944",  
    },
    "19": {
        # Landing helipad for high workload scenario
        "name": "Old Fourth Ward Children's Heliport ",
        "id": "GA4W",
        "location": "303 Parkway Dr NE, Atlanta, GA 30312",
        "hasHospital": True,
        "nearest": False,
        "nominal":False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        # "latitude": "33.7626693", original
        # "longitude": "-84.3739344", original
        "latitude": "33.76400330983825", # offset for visibility
        "longitude": "-84.37359282618218", #offset for visibility , 
    },
    "20": {
        "name": "Fulton County Executive Airport ",
        "id": "FTY",
        "location": "3977 Aviation Cir NW, Atlanta, GA 30336",
        "hasHospital": False,
        "nearest": False, #to be set as true for higher workload scenario
        "nominal": False,
        "nominal_departure": False,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7791264",
        "longitude": "-84.5213660",
    },
    "21": {
        # Departure Location
        "name": "Miller Farm, Airport ",
        "id": "25GA",
        "location": "5300 Leann Dr, Douglasville, GA 30135",
        "hasHospital": False,
        "nearest": False, #to be set as true for higher workload scenario
        "nominal": False,
        "nominal_departure": True,
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.6595539", 
        "longitude": "-84.6629889",
    },
    "22": {
        #other scenarios- Emory University
        # Departure for all scenario 
        # 25GA Miller Farm, Dougsville  to old forth
        #https://www.google.com/maps/dir/Miller+Farm+Airport-25GA,+Leann+Dr,+Douglasville,+GA/Fulton+County+Airport+-+Brown+Field+(FTY),+Aviation+Circle+Northwest,+Atlanta,+GA/Old+Fourth+Ward,+Atlanta,+GA/@33.718646,-84.6019543,30007m/data=!3m3!1e3!4b1!5s0x88f5038ebeea134f:0x78787416707158e5!4m20!4m19!1m5!1m1!1s0x88f4df6cae05f855:0xfce85469926264b5!2m2!1d-84.6629511!2d33.6598811!1m5!1m1!1s0x88f51bfd379c09f7:0xdebb7dfce7c9c439!2m2!1d-84.5216729!2d33.7771801!1m5!1m1!1s0x88f50408dbf17f1f:0x60ccf34413430e69!2m2!1d-84.3719735!2d33.7639588!3e0?entry=ttu
        "name": "HCA Parkway Medical Center Heliport ",
        "id": "6GA3",
        "location": "999 Crestmark Blvd, Lithia Springs, GA 301223",
        "hasHospital": False,
        "nearest": False, 
        "nominal": False,
        "nominal_departure": False, 
        "image1": "../static/HAIInterface/img/Mary1.png",
        "image2": "../static/HAIInterface/img/Emory.png",
        "latitude": "33.7780556",
        "longitude": "-84.6113889",	
    }
}
